-- Insert new indicator metadata before loading demographics
-- Run this BEFORE load_demographics.py

INSERT INTO indicator_metadata (indicator_code, name, source_id, category) VALUES
('WB:SP.POP.TOTL.FE.IN', 'Population, female', 1, 'Health'),
('WB:SP.POP.TOTL.MA.IN', 'Population, male', 1, 'Health'),
('WB:SP.POP.TOTL.MA.ZS', 'Population, male (% of total population)', 1, 'Health'),
('WB:SP.POP.DPND.OL', 'Age dependency ratio, old (% of working-age population)', 1, 'Health'),
('WB:SP.POP.DPND.YG', 'Age dependency ratio, young (% of working-age population)', 1, 'Health'),
('WB:SP.POP.0014.FE.IN', 'Population ages 0-14, female', 1, 'Health'),
('WB:SP.POP.0014.MA.IN', 'Population ages 0-14, male', 1, 'Health'),
('WB:SP.POP.1564.FE.IN', 'Population ages 15-64, female', 1, 'Health'),
('WB:SP.POP.1564.MA.IN', 'Population ages 15-64, male', 1, 'Health'),
('WB:SP.POP.65UP.FE.IN', 'Population ages 65 and above, female', 1, 'Health'),
('WB:SP.POP.65UP.MA.IN', 'Population ages 65 and above, male', 1, 'Health'),
('WB:SP.POP.0014.FE.ZS', 'Population ages 0-14, female (% of female population)', 1, 'Health'),
('WB:SP.POP.0014.MA.ZS', 'Population ages 0-14, male (% of male population)', 1, 'Health'),
('WB:SP.POP.1564.FE.ZS', 'Population ages 15-64, female (% of female population)', 1, 'Health'),
('WB:SP.POP.1564.MA.ZS', 'Population ages 15-64, male (% of male population)', 1, 'Health'),
('WB:SP.POP.65UP.FE.ZS', 'Population ages 65 and above, female (% of female population)', 1, 'Health'),
('WB:SP.POP.65UP.MA.ZS', 'Population ages 65 and above, male (% of male population)', 1, 'Health'),
('WB:SP.POP.0004.FE.5Y', 'Population ages 00-04, female (% of female population)', 1, 'Health'),
('WB:SP.POP.0509.FE.5Y', 'Population ages 05-09, female (% of female population)', 1, 'Health'),
('WB:SP.POP.1014.FE.5Y', 'Population ages 10-14, female (% of female population)', 1, 'Health'),
('WB:SP.POP.1519.FE.5Y', 'Population ages 15-19, female (% of female population)', 1, 'Health'),
('WB:SP.POP.2024.FE.5Y', 'Population ages 20-24, female (% of female population)', 1, 'Health'),
('WB:SP.POP.2529.FE.5Y', 'Population ages 25-29, female (% of female population)', 1, 'Health'),
('WB:SP.POP.3034.FE.5Y', 'Population ages 30-34, female (% of female population)', 1, 'Health'),
('WB:SP.POP.3539.FE.5Y', 'Population ages 35-39, female (% of female population)', 1, 'Health'),
('WB:SP.POP.4044.FE.5Y', 'Population ages 40-44, female (% of female population)', 1, 'Health'),
('WB:SP.POP.4549.FE.5Y', 'Population ages 45-49, female (% of female population)', 1, 'Health'),
('WB:SP.POP.5054.FE.5Y', 'Population ages 50-54, female (% of female population)', 1, 'Health'),
('WB:SP.POP.5559.FE.5Y', 'Population ages 55-59, female (% of female population)', 1, 'Health'),
('WB:SP.POP.6064.FE.5Y', 'Population ages 60-64, female (% of female population)', 1, 'Health'),
('WB:SP.POP.6569.FE.5Y', 'Population ages 65-69, female (% of female population)', 1, 'Health'),
('WB:SP.POP.7074.FE.5Y', 'Population ages 70-74, female (% of female population)', 1, 'Health'),
('WB:SP.POP.7579.FE.5Y', 'Population ages 75-79, female (% of female population)', 1, 'Health'),
('WB:SP.POP.80UP.FE.5Y', 'Population ages 80 and above, female (% of female population)', 1, 'Health'),
('WB:SP.POP.0004.MA.5Y', 'Population ages 00-04, male (% of male population)', 1, 'Health'),
('WB:SP.POP.0509.MA.5Y', 'Population ages 05-09, male (% of male population)', 1, 'Health'),
('WB:SP.POP.1014.MA.5Y', 'Population ages 10-14, male (% of male population)', 1, 'Health'),
('WB:SP.POP.1519.MA.5Y', 'Population ages 15-19, male (% of male population)', 1, 'Health'),
('WB:SP.POP.2024.MA.5Y', 'Population ages 20-24, male (% of male population)', 1, 'Health'),
('WB:SP.POP.2529.MA.5Y', 'Population ages 25-29, male (% of male population)', 1, 'Health'),
('WB:SP.POP.3034.MA.5Y', 'Population ages 30-34, male (% of male population)', 1, 'Health'),
('WB:SP.POP.3539.MA.5Y', 'Population ages 35-39, male (% of male population)', 1, 'Health'),
('WB:SP.POP.4044.MA.5Y', 'Population ages 40-44, male (% of male population)', 1, 'Health'),
('WB:SP.POP.4549.MA.5Y', 'Population ages 45-49, male (% of male population)', 1, 'Health'),
('WB:SP.POP.5054.MA.5Y', 'Population ages 50-54, male (% of male population)', 1, 'Health'),
('WB:SP.POP.5559.MA.5Y', 'Population ages 55-59, male (% of male population)', 1, 'Health'),
('WB:SP.POP.6064.MA.5Y', 'Population ages 60-64, male (% of male population)', 1, 'Health'),
('WB:SP.POP.6569.MA.5Y', 'Population ages 65-69, male (% of male population)', 1, 'Health'),
('WB:SP.POP.7074.MA.5Y', 'Population ages 70-74, male (% of male population)', 1, 'Health'),
('WB:SP.POP.7579.MA.5Y', 'Population ages 75-79, male (% of male population)', 1, 'Health'),
('WB:SP.POP.80UP.MA.5Y', 'Population ages 80 and above, male (% of male population)', 1, 'Health'),
('WB:SP.POP.BRTH.MF', 'Sex ratio at birth (male births per female births)', 1, 'Health'),
('WB:SP.ADO.TFRT', 'Adolescent fertility rate (births per 1,000 women ages 15-19)', 1, 'Health'),
('WB:SM.POP.RHCR.EA', 'Refugees under the mandate of the UNHCR by country or territory of asylum', 1, 'Social Protection & Labor'),
('WB:SM.POP.RHCR.EO', 'Refugees under the mandate of the UNHCR by country or territory of origin', 1, 'Social Protection & Labor')
ON CONFLICT (indicator_code) DO NOTHING;
